POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impha2UxMjMiLCJpZCI6IjY5NmM1ZDRmNTBlZWQ3ODRjMjkxMzYyMyIsImlhdCI6MTc2ODczODczMSwiZXhwIjoxNzY4NzQyMzMxfQ.j0xpd0NpcaXfu23cMkydkHoc9E-M_MpK4dDWjG0BQgQ

{
  "title": "Max",
  "author": "NoOne",
  "url": "http://sample.url.com",
  "likes": 5,
  "user": "696b927bb2b3a5a805c54e16"
}