POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1bGVzdSIsImlkIjoiNjk2Y2ZhMzg4Yzg5YzljYWQ4YTdlNWY2IiwiaWF0IjoxNzY4NzQ5NjQxLCJleHAiOjE3Njg3NTMyNDF9.d5wnMnp423e3NfsIqTK4prjafLPctr3F_DeKpoF8hg0

{
  "title": "A Will Eternal",
  "author": "Er Gen",
  "url": "https://www.wuxiaworld.com/novel/a-will-eternal",
  "likes": 222
}